#!/usr/bin/env python
import pprint
from src.populated_galaxy_systems import PopulatedGalaxySystems


DEBUG_SYSTEM = "Chamas"
system = PopulatedGalaxySystems().get_system(DEBUG_SYSTEM)
pprint.pprint(system, depth=1)
pprint.pprint(system.factions)
pprint.pprint(system.stations, depth=3)

for body in system.bodies:
    if body.name != "Chamas C 7":
        continue
    pprint.pprint(body, depth=2)
