#!/usr/bin/env python

import argparse
import pprint
import textwrap

from src.ed_types import Coordinates, Minerals
from src.populated_galaxy_systems import PopulatedGalaxySystems
from src.powerplay_systems import PowerplaySystems
from src.timer import Timer
from src.utils import StoreSystemNameWithCoords

def parse_args():
    argparser = argparse.ArgumentParser(__name__, formatter_class=argparse.RawDescriptionHelpFormatter, description=textwrap.dedent('''\
    Hypothesis: There are acquirable systems that have elevated prices but we don't know about them because of data staleness.

    Faction state (Boom) information is revealed when entering a system, which is much more likely than exact
    commodity prices which requires a CMDR to dock at a specific station.

    As such, there exists a time delta between freshness of faction states and known commodity market prices.
    This script tries to analyze this delta for potential stations to check prices at for advantageous PP2.0 play

    Key points:
    - The fresher the faction state (Eg, Boom), the better
    - Market data staleness isn't strictly required, but the fresher the data the more likely it'll just show up on meritminer.cc normally.

    Finds acquisition systems/stations that:
    - Has a minimum landing pad size of MIN_LANDING_PAD
    - Has a minimum population of MIN_POPULATION (Encourages higher commodity demand)
    - Is in Boom
        - Has a market with data older than MIN_MARKET_DATA_AGE_IN_DAYS
        - Buys/Sells commodities in TARGET_COMMODITIES
    - In range of a reinforcement system
      - Reinforcement system has at least one TARGET MINERAL hotspot
    '''))
    argparser.set_defaults(current_system="Sol", current_coords=Coordinates(0, 0, 0))
    argparser.add_argument("--min-market-data-age", action="store", type=int, help="Minimum age of market data", default=3)
    argparser.add_argument("--max-system-data-age", action="store", type=int, help="Maximum age of system/faction state data", default=2)
    argparser.add_argument("--min-landing-pad-size", action="store", type=str, help="Minimum landing pad size", choices=["large", "medium", "small"], default="medium")
    argparser.add_argument("--target-commodity", dest="target_commodities", action="append", type=Minerals, help="Mineral commodities to target for mining", choices=[ enum.value for enum in Minerals], default=["Monazite", "Platinum"])
    argparser.add_argument("--max-distance", action="store", type=int, help="Max distance in LY to search", default=250)
    argparser.add_argument("--min-population", action="store", type=int, help="Min population of target acquisition system. Higher population generally means higher commodity demand", default=100000)
    argparser.add_argument("--current-system", action=StoreSystemNameWithCoords, type=str, help="Current system name. If we don't know about this system, will default to Sol coords", default="Sol")
    argparser.add_argument("--debug", action="store_true")

    return argparser.parse_args()


def find_reinforceable_systems(args: argparse.Namespace):
    # Exploited or Fortified systems in Boom under Nakato Kaine control
    with Timer("powerplay_systems.get_reinforcement_systems()"):
        boom_reinforcement_pp_systems = PowerplaySystems.get_reinforcement_systems(
            "Nakato Kaine",
            ["Exploited", "Fortified", "Stronghold"],
            ["Boom"],
            maxAgeInDays=args.max_system_data_age,
        )
    with Timer(f"db_hydration_timer - {len(boom_reinforcement_pp_systems)} systems"):
        boom_reinforcement_systems = PopulatedGalaxySystems.get_systems(list(map(lambda sys: sys.name, boom_reinforcement_pp_systems)))

    # Filter for unoccupied systems above minimum population and has at least one valid hotspot
    reinforceable_systems = [
        system
        for system in boom_reinforcement_systems
        if system.population > args.min_population
        and system.get_hotspot_rings(
            [Minerals.Platinum, Minerals.Monazite]
        )
    ]

    # Sort by distance
    reinforceable_systems.sort(
        reverse=True,
        key=lambda system: args.current_coords.distance_to(system.coords),
    )

    return reinforceable_systems

def run(args: argparse.Namespace):
    systems_count = 0
    stations_count = 0
    for system in find_reinforceable_systems(args):
        all_stations = system.get_stations_with_services(["Market"])

        stations = [
            station
            for station in all_stations
            if station.has_commodities(args.target_commodities, require_all=False)
            and station.has_minimum_landing_pad(args.min_landing_pad_size)
            and station.has_min_data_age_days(args.min_market_data_age)
        ]

        if stations:
            ring_hotspots = system.get_hotspot_rings(
                [Minerals.Platinum, Minerals.Monazite]
            )
            print("")
            print("")
            print("===============================")
            print("=        REINFORCEMENT?       =")
            print("=========== SYSTEM ============")
            print(f"Name: {system.name} ({system.powerState})")
            print(
                f"Distance: {args.current_coords.distance_to(system.coords):.2f}LY"
            )
            print(f"Updated: {system.date}")
            print(f"Population: {system.population}")
            print(f"Controlling Faction: {pprint.pformat(max(system.factions, key = lambda f: f.influence))}")
            for ring_name, hotspots in ring_hotspots.items():
                print(f"++ {ring_name} ++")
                for mineral_type, hotspot_count in hotspots.items():
                    print(f"  > {mineral_type}: {hotspot_count} Hotspots")
            if args.debug:
                pprint.pprint(system, depth=2)

        for station in stations:
            print("")
            print("== STATION")
            print(f">> Name: {station.name} ({station.distanceToArrival:.2f}LS)")
            print(f">> Updated: {station.updateTime.isoformat()}")
            print(f">> Economies: {station.economies}")
            print(f">> Controlling Faction Name: {pprint.pformat(station.controllingFaction)}")
            print(f">> Controlling Faction State: {pprint.pformat(station.controllingFactionState)}")
            for commodity in args.target_commodities:
                print(
                    f"  !! {commodity} !! {pprint.pformat(station.get_commodity_price(commodity))}"
                )
            if args.debug:
                pprint.pprint(station, depth=2)


        if stations:
            systems_count += 1
            stations_count += len(stations)

    print("")
    print("=============")
    print(f"Systems: {systems_count}")
    print(f"Stations: {stations_count}")


if __name__ == "__main__":
    with Timer("Script"):
        run(parse_args())
