from constants import GALAXY_POPULATED
from populated_galaxy_systems_importer import PopulatedGalaxySystemsImporter

filterer = PopulatedGalaxySystemsImporter(GALAXY_POPULATED)
filterer.filter_and_import_systems()
