from enum import Enum
from typing import Any, Callable

class StrEnum(Enum): ...

def enum(*, value: str, **metadata: Any) -> Enum: ...
def member(*, value: str, **metadata: Any) -> Callable[[Any], Any]: ...
