from enum import Enum
from typing import Any, Callable

class StrEnum(str, Enum): ...

def enum(*, value: str, **metadata: Any) -> Any: ...
def member(*, value: str, **metadata: Any) -> Callable[[Any], Any]: ...
