{
 "title": "Global Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kaine Mining Acquisition Routes",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with acquisition_vectors as (\n    select *\n    from derived.get_systems_with_power_and_state('Nakato Kaine', array ['Fortified', 'Stronghold'])\n), unoccupied_systems as (\n    select *\n    from core.systems\n    where 'Nakato Kaine' = any(powers)\n    and power_state = 'Unoccupied'\n), all_acquisition_routes as (\n\tselect\n\t\tav.name as acquisition_vector,\n\t\tav.id as acquisition_vector_id,\n\t\tav.power_state as vector_state,\n\t\tus.name as acquisition_target,\n\t\tus.id as acquisition_target_id,\n\t\tus.power_state as target_state,\n\t\tst_3ddistance(av.coords, us.coords) as distance\n\tfrom acquisition_vectors as av\n\tjoin unoccupied_systems as us on st_3ddwithin(\n\t\tav.coords, \n\t\tus.coords, \n\t\tcase when av.power_state = 'Stronghold' then 30 else 20 end\n\t)\n), acquisition_routes_with_hotspots as (\n\tselect *\n\tfrom all_acquisition_routes aar\n\tjoin derived.hotspot_ring_view hrv on hrv.system_name = aar.acquisition_vector\n\twhere hrv.commodity in ('Monazite', 'Platinum')\n), acquisition_routes_with_hotspots_and_markets as (\n\tselect *\n\tfrom acquisition_routes_with_hotspots arh\n\tjoin derived.station_commodities_view scv on arh.acquisition_target = scv.system_name\n\twhere arh.commodity = scv.commodity_sym\n\tand scv.updated_at > (NOW() - interval '2 days')\n), ranked_stations AS (\n  SELECT\n    *,\n    ROW_NUMBER() OVER (\n      PARTITION BY acquisition_vector, acquisition_target, commodity\n      ORDER BY sell_price DESC NULLS LAST\n    ) AS station_rank\n  FROM acquisition_routes_with_hotspots_and_markets\n), top_station_rows AS (\n  SELECT *\n  FROM ranked_stations\n  WHERE station_rank <= 1\n)\nSELECT\n  concat(acquisition_vector, ' (', vector_state, ')') as vector_system,\n  acquisition_target as target_unoccupied_system,\n  concat(round(min(distance)::numeric, 2), ' LY') AS distance,\n  commodity,\n  station_name, sell_price, demand, updated_at\nFROM top_station_rows\nGROUP BY\n  acquisition_vector, vector_state, acquisition_target, commodity, station_name, sell_price, demand, updated_at\nORDER BY acquisition_vector, acquisition_target;"
    }
   ]
  },
  {
   "title": "Kaine Mining Acquisition Routes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "with acquisition_vectors as (\n    select *\n    from derived.get_systems_with_power_and_state('Nakato Kaine', array ['Fortified', 'Stronghold'])\n), unoccupied_systems as (\n    select *\n    from core.systems\n    where 'Nakato Kaine' = any(powers)\n    and power_state = 'Unoccupied'\n), all_acquisition_routes as (\n\tselect\n\t\tav.name as acquisition_vector,\n\t\tav.id as acquisition_vector_id,\n\t\tav.power_state as vector_state,\n\t\tus.name as acquisition_target,\n\t\tus.id as acquisition_target_id,\n\t\tus.power_state as target_state,\n\t\tst_3ddistance(av.coords, us.coords) as distance\n\tfrom acquisition_vectors as av\n\tjoin unoccupied_systems as us on st_3ddwithin(\n\t\tav.coords, \n\t\tus.coords, \n\t\tcase when av.power_state = 'Stronghold' then 30 else 20 end\n\t)\n), acquisition_routes_with_hotspots as (\n\tselect *\n\tfrom all_acquisition_routes aar\n\tjoin derived.hotspot_ring_view hrv on hrv.system_name = aar.acquisition_vector\n\twhere hrv.commodity in ('Monazite', 'Platinum')\n), acquisition_routes_with_hotspots_and_markets as (\n\tselect *\n\tfrom acquisition_routes_with_hotspots arh\n\tjoin derived.station_commodities_view scv on arh.acquisition_target = scv.system_name\n\twhere arh.commodity = scv.commodity_sym\n\tand scv.updated_at > (NOW() - interval '3 days')\n), ranked_stations AS (\n  SELECT\n    *,\n    ROW_NUMBER() OVER (\n      PARTITION BY acquisition_vector, acquisition_target, commodity\n      ORDER BY sell_price DESC NULLS LAST\n    ) AS station_rank\n  FROM acquisition_routes_with_hotspots_and_markets\n), top_station_rows AS (\n  SELECT *\n  FROM ranked_stations\n  WHERE station_rank <= 1\n)\nSELECT\n  concat(acquisition_vector, ' (', vector_state, ')') as vector_system,\n  acquisition_target as target_system,\n  concat(round(min(distance)::numeric, 2), ' LY') AS distance,\n  array_agg(DISTINCT ring_name) AS ring_names,\n  array_agg(DISTINCT ring_type) AS ring_types,\n  commodity,\n  station_name, sell_price, demand, updated_at\nFROM top_station_rows\nGROUP BY\n  acquisition_vector, vector_state, acquisition_target, commodity, station_name, sell_price, demand, updated_at\nORDER BY acquisition_vector, acquisition_target;"
    }
   ]
  },
  {
   "title": "Kaine AS/RS Detected Entering Boom Last 3 Days",
   "type": "table",
   "description": "Lists any Kaine-influenced AS/RS that were detected as having entered a Boom state in the last 72 hours from a non-Boom state.\n\nDetection relies on a transition into Boom state via EDDN messages rather than directly checking the current known state of factions",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "\nWITH ranked_state_changes AS (\n  SELECT\n    LAG(fp.state) OVER (PARTITION BY fp.faction_id, fp.system_id ORDER BY fp.timestamp) AS previous_state,\n    fp.*\n  FROM timescaledb.faction_presences fp\n  WHERE fp.timestamp > NOW() - INTERVAL '3 days'\n),\nlatest_boom_transitions AS (\n  SELECT *\n  FROM (\n    SELECT *,\n           ROW_NUMBER() OVER (PARTITION BY system_id ORDER BY timestamp DESC) AS rn\n    FROM ranked_state_changes\n    WHERE state = 'Boom' AND previous_state <> 'Boom'\n  ) t\n  WHERE rn = 1\n)\nSELECT\n  s.name AS system_name,\n  f.name AS faction_name,\n  s.power_state,\n  s.population,\n  fp.state,\n  fp.active_states,\n  fp.pending_states,\n  fp.updated_at AS states_updated_at,\n  sc.timestamp AS detected_boom_at,\n  (NOW() - sc.timestamp) AS time_in_boom\nFROM latest_boom_transitions sc\nJOIN core.systems s ON s.id = sc.system_id\nJOIN core.faction_presences fp ON fp.system_id = s.id AND fp.faction_id = s.controlling_faction_id\nJOIN core.factions f ON f.id = s.controlling_faction_id\nWHERE fp.state = 'Boom'\n  AND (\n    s.controlling_power = 'Nakato Kaine'\n    OR ('Nakato Kaine' = ANY(s.powers) AND s.power_state = 'Unoccupied')\n)\nORDER BY system_name;"
    }
   ]
  },
  {
   "title": "Kaine AS/RS Systems Currently In Boom",
   "type": "table",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "select s.name, s.power_state, fp.state, fp.updated_at\nfrom core.systems s\njoin core.faction_presences fp \non s.id = fp.system_id\nand s.controlling_faction_id = fp.faction_id\nwhere 'Boom' = fp.state\nand (now() - fp.updated_at) < interval '2 days'\nand (s.controlling_power = 'Nakato Kaine' or ('Nakato Kaine' = any(s.powers) and s.power_state = 'Unoccupied'))\norder by s.name\n;"
    }
   ]
  }
 ]
}