from enum import StrEnum


class CommodityCategory(StrEnum):
    CHEMICALS = "Chemicals"
    CONSUMER_ITEMS = "Consumer Items"
    LEGAL_DRUGS = "Legal Drugs"
    FOODS = "Foods"
    INDUSTRIAL_MATERIALS = "Industrial Materials"
    MACHINERY = "Machinery"
    MEDICINES = "Medicines"
    METALS = "Metals"
    MINERALS = "Minerals"
    SALVAGE = "Salvage"
    SLAVERY = "Slavery"
    TECHNOLOGY = "Technology"
    TEXTILES = "Textiles"
    WASTE = "Waste"
    WEAPONS = "Weapons"


class Chemicals(StrEnum):
    TRITIUM = "Tritium"
    ARGONOMIC_TREATMENT = "Argonomic Treatment"
    EXPLOSIVES = "Explosives"
    HYDROGEN_FUEL = "Hydrogen Fuel"
    LIQUID_FUEL = "Liquid Fuel"
    MINERAL_OIL = "Mineral Oil"
    NERVE_AGENTS = "Nerve Agents"
    PESTICIDES = "Pesticides"
    ROCKFORTH_FERTILISER = "Rockforth Fertiliser"
    SURFACE_STABILISERS = "Surface Stabilisers"
    SYNTHETIC_REAGENTS = "Synthetic Reagents"
    WATER = "Water"


class Minerals(StrEnum):
    ALEXANDRITE = "Alexandrite"
    BAUXITE = "Bauxite"
    BENITOITE = "Benitoite"
    BERTRANDITE = "Bertrandite"
    BROMELLITE = "Bromellite"
    COLTAN = "Coltan"
    CRYOLITE = "Cryolite"
    GALLITE = "Gallite"
    GOSLARITE = "Goslarite"
    GRANDIDIERITE = "Grandidierite"
    HAEMATITE = "Haematite"
    INDITE = "Indite"
    JADEITE = "Jadeite"
    LEPIDOLITE = "Lepidolite"
    LITHIUM_HYDROXIDE = "Lithium Hydroxide"
    LOW_TEMPERATURE_DIAMONDS = "Low Temperature Diamonds"
    METHANE_CLATHRATE = "Methane Clathrate"
    METHANOL_MONOHYDRATE_CRYSTALS = "Methanol Monohydrate Crystals"
    MOISSANITE = "Moissanite"
    MONAZITE = "Monazite"
    MUSGRAVITE = "Musgravite"
    PAINITE = "Painite"
    PYROPHYLLITE = "Pyrophyllite"
    RHODPLUMSITE = "Rhodplumsite"
    RUTILE = "Rutile"
    SERENDIBITE = "Serendibite"
    TAAFFEITE = "Taaffeite"
    URANINITE = "Uraninite"
    VOID_OPAL = "Void Opal"


class Metals(StrEnum):
    ALUMINIUM = "Aluminium"
    BERYLLIUM = "Beryllium"
    BISMUTH = "Bismuth"
    COBALT = "Cobalt"
    COPPER = "Copper"
    GALLIUM = "Gallium"
    GOLD = "Gold"
    HAFNIUM_178 = "Hafnium 178"
    INDIUM = "Indium"
    LANTHANUM = "Lanthanum"
    LITHIUM = "Lithium"
    OSMIUM = "Osmium"
    PALLADIUM = "Palladium"
    PLATINUM = "Platinum"
    PRASEODYMIUM = "Praseodymium"
    SAMARIUM = "Samarium"
    SILVER = "Silver"
    STEEL = "Steel"
    TANTALUM = "Tantalum"
    THALLIUM = "Thallium"
    THORIUM = "Thorium"
    TITANIUM = "Titanium"
    URANIUM = "Uranium"
