---
services:
  postgres:
    container_name: ekaine_db
    image: timescale/timescaledb-ha:pg17
    restart: always
    environment:
      POSTGRES_USER: ekaine
      POSTGRES_PASSWORD: ekaine_pw
      POSTGRES_DB: ekaine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ekaine"]
      interval: 10s
      timeout: 10s
      retries: 15
    ports: ["${PG_PORT:-5432}:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  grafana:
    container_name: ekaine_grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports: [3000:3000]
    volumes:
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  setup:
    container_name: ekaine_setup
    image: remiscarlet/ekaine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://ekaine:ekaine_pw@postgres:${PG_PORT:-5432}/ekaine
    entrypoint: ["bash", "-c", "pwd && ls -al && make setup-container && make hydrate-db"]
    restart: "no"
    volumes:
      - ../../tools/:/app/tools
      - ../../src/:/app/src
      - ../../Makefile:/app/Makefile

  app:
    container_name: ekaine_app
    image: remiscarlet/ekaine
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
      setup:
       condition: service_completed_successfully
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    environment:
      DATABASE_URL: postgresql://ekaine:ekaine_pw@postgres:${PG_PORT:-5432}/ekaine
    ports: [8000:8000]

volumes:
  pgdata:
  pg-data:
  grafana-data:
